//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinary_Clinic.Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int PrescriptionID { get; set; }
        public int PatientID { get; set; }
        public int DiseaseID { get; set; }
        public string Inscription { get; set; }
        public Nullable<int> I_O_Hospital_ID { get; set; }
        public Nullable<int> OperationID { get; set; }
        public Nullable<int> PrescriptionDrugID { get; set; }
        public Nullable<System.DateTime> InHospital { get; set; }
        public Nullable<System.DateTime> OutHospital { get; set; }
        public int I_O_Fee { get; set; }
        public int Operation_Fee { get; set; }
        public int Drug_Fee { get; set; }
        public int Total_Fee { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual I_O_Hospital I_O_Hospital { get; set; }
        public virtual Operation Operation { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual PrescriptionDrug PrescriptionDrug { get; set; }
    }
}
