//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veterinary_Clinic.Library
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VETEntities : DbContext
    {
        public VETEntities()
            : base("name=VETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Breeds> Breeds { get; set; }
        public virtual DbSet<Companion> Companion { get; set; }
        public virtual DbSet<Disease> Disease { get; set; }
        public virtual DbSet<Drug> Drug { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<I_O_Hospital> I_O_Hospital { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<Prescription> Prescription { get; set; }
        public virtual DbSet<PrescriptionDrug> PrescriptionDrug { get; set; }
        public virtual DbSet<Species> Species { get; set; }
    }
}
